export interface SamplePrompt {
  id: string;
  text: string;
  description: string;
}

export interface PromptSector {
  id: string;
  label: string;
  icon: string;
  prompts: SamplePrompt[];
}

export const promptSectors: PromptSector[] = [
  {
    id: 'analysis',
    label: 'Data Analysis',
    icon: 'BarChart3',
    prompts: [
      { id: 'a1', text: 'Profile all columns and summarize data quality', description: 'Full column-level profiling with types, nulls, and distributions' },
      { id: 'a2', text: 'Show the distribution of each numeric column', description: 'Histograms and density plots for all numeric features' },
      { id: 'a3', text: 'Find the top 10 most correlated feature pairs', description: 'Pearson correlation matrix with ranked pairs' },
      { id: 'a4', text: 'Identify all missing values and suggest imputation strategies', description: 'Null analysis with MCAR/MAR/MNAR classification' },
      { id: 'a5', text: 'Detect outliers using IQR and Z-score methods', description: 'Multi-method outlier detection with flagging' },
      { id: 'a6', text: 'Generate a comprehensive summary statistics table', description: 'Mean, median, mode, std, skewness, kurtosis per column' },
      { id: 'a7', text: 'Create a pivot table grouped by the top categorical column', description: 'Aggregated pivot with counts and percentages' },
      { id: 'a8', text: 'Show value counts for all categorical columns', description: 'Frequency tables with bar chart visualizations' },
      { id: 'a9', text: 'Calculate the skewness and kurtosis of all numeric features', description: 'Distribution shape analysis for normality assessment' },
      { id: 'a10', text: 'Run a time series decomposition if there is a date column', description: 'Trend, seasonality, and residual components' },
      { id: 'a11', text: 'Compare distributions across different groups in the data', description: 'Group-wise statistical comparisons' },
      { id: 'a12', text: 'Find duplicate rows and assess their impact', description: 'Exact and fuzzy duplicate detection' },
      { id: 'a13', text: 'Create a correlation heatmap for all numeric columns', description: 'Visual correlation matrix with color coding' },
      { id: 'a14', text: 'Perform a Pareto analysis on the top categorical column', description: '80/20 rule analysis with cumulative chart' },
      { id: 'a15', text: 'Generate box plots for all numeric columns', description: 'Five-number summary visualization' },
      { id: 'a16', text: 'Identify columns with low variance that could be dropped', description: 'Near-constant feature detection' },
      { id: 'a17', text: 'Show the data types and memory usage of each column', description: 'Schema inspection with optimization suggestions' },
      { id: 'a18', text: 'Calculate percentile ranks for the target column', description: 'Percentile distribution analysis' },
      { id: 'a19', text: 'Run a chi-squared test between categorical columns', description: 'Statistical independence testing' },
      { id: 'a20', text: 'Create scatter plots for the top 5 most correlated pairs', description: 'Visual relationship exploration' },
      { id: 'a21', text: 'Analyze the cardinality of each column', description: 'Unique value counts and high-cardinality flagging' },
      { id: 'a22', text: 'Show the first and last 20 rows side by side', description: 'Head/tail comparison for data inspection' },
      { id: 'a23', text: 'Calculate rolling averages for numeric time series columns', description: 'Moving average trend analysis' },
      { id: 'a24', text: 'Segment the data into quantile-based bins', description: 'Equal-frequency binning for numeric columns' },
      { id: 'a25', text: 'Find columns that are perfectly correlated (redundant)', description: 'Multicollinearity detection' },
      { id: 'a26', text: 'Generate a data quality scorecard', description: 'Completeness, accuracy, consistency metrics' },
      { id: 'a27', text: 'Perform cohort analysis if timestamps are available', description: 'User/entity cohort tracking over time' },
      { id: 'a28', text: 'Run ANOVA across groups for numeric columns', description: 'Analysis of variance for group differences' },
      { id: 'a29', text: 'Create a cumulative distribution function plot', description: 'CDF visualization for numeric features' },
      { id: 'a30', text: 'Identify seasonal patterns in the data', description: 'Seasonality detection with autocorrelation' },
      { id: 'a31', text: 'Compare before and after distributions for a transformation', description: 'Distribution comparison with KS test' },
      { id: 'a32', text: 'Calculate the coefficient of variation for all numeric columns', description: 'Relative variability measurement' },
      { id: 'a33', text: 'Find the most common patterns in string columns', description: 'Regex pattern extraction and frequency analysis' },
      { id: 'a34', text: 'Generate a detailed null pattern matrix', description: 'Missingness co-occurrence visualization' },
      { id: 'a35', text: 'Create a violin plot for key numeric columns', description: 'Distribution shape with density estimation' },
      { id: 'a36', text: 'Perform a Grubbs test for outlier detection', description: 'Statistical outlier test with significance levels' },
      { id: 'a37', text: 'Analyze the entropy of categorical columns', description: 'Information content and randomness measurement' },
      { id: 'a38', text: 'Build a cross-tabulation between two categorical columns', description: 'Contingency table with marginal totals' },
      { id: 'a39', text: 'Calculate Cramers V for all categorical pairs', description: 'Association strength between categoricals' },
      { id: 'a40', text: 'Show the rate of change over time for numeric columns', description: 'First derivative analysis for trends' },
      { id: 'a41', text: 'Create a pair plot for the top 6 numeric features', description: 'Scatterplot matrix with histograms' },
      { id: 'a42', text: 'Identify potential data entry errors in string columns', description: 'Typo and inconsistency detection' },
      { id: 'a43', text: 'Perform a normality test on all numeric columns', description: 'Shapiro-Wilk and Anderson-Darling tests' },
      { id: 'a44', text: 'Calculate the Gini coefficient for inequality analysis', description: 'Distribution inequality measurement' },
      { id: 'a45', text: 'Show the top 10 rows by each numeric column', description: 'Extreme value inspection' },
      { id: 'a46', text: 'Analyze weekday vs weekend patterns if dates exist', description: 'Day-of-week behavioral analysis' },
      { id: 'a47', text: 'Create a sunburst chart for hierarchical categorical data', description: 'Multi-level categorical breakdown' },
      { id: 'a48', text: 'Run a Mann-Whitney U test between two groups', description: 'Non-parametric group comparison' },
      { id: 'a49', text: 'Calculate mutual information between all feature pairs', description: 'Non-linear dependency measurement' },
      { id: 'a50', text: 'Generate an executive summary of the dataset in plain English', description: 'Business-friendly data overview' },
      { id: 'a51', text: 'Identify the most predictive features for a target variable', description: 'Feature importance ranking' },
      { id: 'a52', text: 'Show year-over-year growth rates', description: 'Annual growth trend analysis' },
    ],
  },
  {
    id: 'science',
    label: 'Data Science',
    icon: 'Brain',
    prompts: [
      { id: 's1', text: 'Suggest the best ML model for this dataset', description: 'Auto-ML style model recommendation based on data shape' },
      { id: 's2', text: 'Build a classification model and show the confusion matrix', description: 'End-to-end classifier with evaluation metrics' },
      { id: 's3', text: 'Perform feature importance analysis using Random Forest', description: 'Tree-based feature ranking with visualization' },
      { id: 's4', text: 'Run PCA and visualize the first two principal components', description: 'Dimensionality reduction with explained variance' },
      { id: 's5', text: 'Build a regression model and evaluate R², MAE, RMSE', description: 'Regression pipeline with comprehensive metrics' },
      { id: 's6', text: 'Perform k-means clustering and show cluster profiles', description: 'Unsupervised segmentation with centroids' },
      { id: 's7', text: 'Generate a train/test split strategy for this data', description: 'Stratified splitting with cross-validation plan' },
      { id: 's8', text: 'Create an XGBoost model with hyperparameter tuning', description: 'Gradient boosting with grid search' },
      { id: 's9', text: 'Build a neural network architecture for this dataset', description: 'Deep learning model design with layer specs' },
      { id: 's10', text: 'Perform SHAP analysis to explain model predictions', description: 'Explainable AI with feature attribution' },
      { id: 's11', text: 'Run a logistic regression with odds ratio interpretation', description: 'Interpretable classification with coefficients' },
      { id: 's12', text: 'Apply SMOTE to handle class imbalance', description: 'Synthetic oversampling for imbalanced datasets' },
      { id: 's13', text: 'Build a time series forecasting model', description: 'ARIMA/Prophet-style prediction pipeline' },
      { id: 's14', text: 'Create a recommendation system based on this data', description: 'Collaborative or content-based filtering' },
      { id: 's15', text: 'Perform hierarchical clustering with dendrogram', description: 'Agglomerative clustering visualization' },
      { id: 's16', text: 'Run a decision tree and visualize the rules', description: 'Interpretable tree with decision paths' },
      { id: 's17', text: 'Apply LASSO regularization for feature selection', description: 'L1 penalty for sparse feature identification' },
      { id: 's18', text: 'Build an ensemble model combining multiple algorithms', description: 'Stacking or voting classifier design' },
      { id: 's19', text: 'Perform sentiment analysis if text columns exist', description: 'NLP sentiment scoring pipeline' },
      { id: 's20', text: 'Create learning curves to diagnose bias vs variance', description: 'Model complexity analysis' },
      { id: 's21', text: 'Apply t-SNE for high-dimensional visualization', description: 'Non-linear dimensionality reduction' },
      { id: 's22', text: 'Build a Bayesian model for uncertainty quantification', description: 'Probabilistic predictions with credible intervals' },
      { id: 's23', text: 'Design a cross-validation strategy with k-fold', description: 'Robust model evaluation pipeline' },
      { id: 's24', text: 'Perform association rule mining (Apriori)', description: 'Market basket analysis with support/confidence' },
      { id: 's25', text: 'Build a survival analysis model if time-to-event data exists', description: 'Kaplan-Meier and Cox proportional hazards' },
      { id: 's26', text: 'Create ROC curves and calculate AUC for classifiers', description: 'Classification threshold analysis' },
      { id: 's27', text: 'Apply polynomial feature engineering and evaluate impact', description: 'Non-linear feature transformation' },
      { id: 's28', text: 'Build a Naive Bayes classifier for text data', description: 'Probabilistic text classification' },
      { id: 's29', text: 'Perform topic modeling with LDA on text columns', description: 'Latent topic discovery in text data' },
      { id: 's30', text: 'Create a model comparison table across 5 algorithms', description: 'Head-to-head model benchmarking' },
      { id: 's31', text: 'Apply KNN with distance metric optimization', description: 'Nearest neighbor classification/regression' },
      { id: 's32', text: 'Build an autoencoder for anomaly detection', description: 'Deep learning anomaly scoring' },
      { id: 's33', text: 'Perform Granger causality testing', description: 'Temporal causal relationship analysis' },
      { id: 's34', text: 'Create precision-recall curves for imbalanced classes', description: 'Imbalanced classification evaluation' },
      { id: 's35', text: 'Build a gradient boosted regression with early stopping', description: 'Optimized boosting with regularization' },
      { id: 's36', text: 'Apply IsolationForest for unsupervised anomaly detection', description: 'Tree-based outlier scoring' },
      { id: 's37', text: 'Generate a model card documenting the best model', description: 'Standardized model documentation' },
      { id: 's38', text: 'Perform ablation study removing features one at a time', description: 'Feature contribution analysis' },
      { id: 's39', text: 'Build a calibration curve for probability predictions', description: 'Prediction reliability assessment' },
      { id: 's40', text: 'Apply embedding techniques for categorical variables', description: 'Entity embedding for high-cardinality features' },
      { id: 's41', text: 'Create a stacked generalization ensemble', description: 'Meta-learner combining base models' },
      { id: 's42', text: 'Perform Bayesian hyperparameter optimization', description: 'Efficient search with Gaussian processes' },
      { id: 's43', text: 'Build a multi-output prediction model', description: 'Simultaneous multi-target regression' },
      { id: 's44', text: 'Apply DBSCAN for density-based clustering', description: 'Non-parametric cluster detection' },
      { id: 's45', text: 'Create partial dependence plots for top features', description: 'Feature effect visualization' },
      { id: 's46', text: 'Build a pipeline with preprocessing and model training', description: 'End-to-end sklearn pipeline design' },
      { id: 's47', text: 'Perform statistical power analysis for sample size', description: 'Minimum sample size calculation' },
      { id: 's48', text: 'Apply data augmentation techniques for small datasets', description: 'Synthetic data generation strategies' },
      { id: 's49', text: 'Build a multi-class classifier with one-vs-rest strategy', description: 'Multi-class classification pipeline' },
      { id: 's50', text: 'Generate a reproducible experiment report', description: 'Full experiment documentation with metrics' },
      { id: 's51', text: 'Perform feature interaction analysis', description: 'Detect synergistic feature combinations' },
    ],
  },
  {
    id: 'engineering',
    label: 'Data Engineering',
    icon: 'Wrench',
    prompts: [
      { id: 'e1', text: 'Design a data pipeline architecture for this dataset', description: 'ETL/ELT pipeline design with stages' },
      { id: 'e2', text: 'Generate SQL CREATE TABLE statements from this schema', description: 'DDL generation with proper types and constraints' },
      { id: 'e3', text: 'Create a feature engineering plan for ML readiness', description: 'Feature transformation and creation strategy' },
      { id: 'e4', text: 'Write data validation rules for each column', description: 'Schema validation with Great Expectations style' },
      { id: 'e5', text: 'Design a data partitioning strategy for scalability', description: 'Partition key selection and scheme design' },
      { id: 'e6', text: 'Generate a dbt model for transforming this data', description: 'dbt SQL model with tests and documentation' },
      { id: 'e7', text: 'Create an Airflow DAG for this data pipeline', description: 'Orchestration workflow with tasks and dependencies' },
      { id: 'e8', text: 'Write data quality checks and assertions', description: 'Automated quality gates with pass/fail criteria' },
      { id: 'e9', text: 'Design a CDC (Change Data Capture) strategy', description: 'Incremental data capture pipeline design' },
      { id: 'e10', text: 'Generate a star schema from this flat dataset', description: 'Dimensional modeling with fact and dimension tables' },
      { id: 'e11', text: 'Create a data catalog entry for this dataset', description: 'Metadata documentation with lineage' },
      { id: 'e12', text: 'Write Python code to clean and standardize this data', description: 'Data cleansing pipeline with pandas' },
      { id: 'e13', text: 'Design an idempotent data loading strategy', description: 'Upsert and merge patterns for reliability' },
      { id: 'e14', text: 'Generate a Spark job for processing this data at scale', description: 'PySpark transformation code' },
      { id: 'e15', text: 'Create data lineage documentation', description: 'Source-to-target mapping with transformations' },
      { id: 'e16', text: 'Write unit tests for the data transformations', description: 'pytest-based data pipeline testing' },
      { id: 'e17', text: 'Design a data lakehouse architecture', description: 'Bronze/Silver/Gold layer design' },
      { id: 'e18', text: 'Generate a schema migration plan for evolving data', description: 'Backward-compatible schema evolution strategy' },
      { id: 'e19', text: 'Create a data anonymization plan for PII columns', description: 'Masking, hashing, and tokenization strategies' },
      { id: 'e20', text: 'Write a streaming pipeline design for real-time data', description: 'Kafka/Kinesis architecture with processing' },
      { id: 'e21', text: 'Design a slowly changing dimension (SCD) strategy', description: 'Type 1/2/3 SCD implementation plan' },
      { id: 'e22', text: 'Generate indexes and optimization for query performance', description: 'Index strategy with query pattern analysis' },
      { id: 'e23', text: 'Create a data retention and archival policy', description: 'Lifecycle management with compliance' },
      { id: 'e24', text: 'Write a data deduplication pipeline', description: 'Exact and fuzzy matching dedup strategy' },
      { id: 'e25', text: 'Design a multi-tenant data architecture', description: 'Tenant isolation with shared infrastructure' },
      { id: 'e26', text: 'Generate a Terraform config for data infrastructure', description: 'IaC for data platform resources' },
      { id: 'e27', text: 'Create a data contract for this dataset', description: 'Producer-consumer agreement with SLAs' },
      { id: 'e28', text: 'Write a backfill strategy for historical data', description: 'Batch processing for missing historical records' },
      { id: 'e29', text: 'Design a data mesh domain boundary', description: 'Domain-driven data ownership model' },
      { id: 'e30', text: 'Generate a monitoring dashboard config for pipelines', description: 'Metrics, alerts, and SLA tracking' },
      { id: 'e31', text: 'Create a data versioning strategy', description: 'Dataset version control with DVC or similar' },
      { id: 'e32', text: 'Write ETL error handling and retry logic', description: 'Fault-tolerant pipeline patterns' },
      { id: 'e33', text: 'Design a data warehouse schema for analytics', description: 'Optimized warehouse with materialized views' },
      { id: 'e34', text: 'Generate a REST API design for serving this data', description: 'API endpoints with pagination and filtering' },
      { id: 'e35', text: 'Create a data freshness monitoring system', description: 'Staleness detection with alerting' },
      { id: 'e36', text: 'Write a data reconciliation check between source and target', description: 'Row count and checksum validation' },
      { id: 'e37', text: 'Design a metadata management strategy', description: 'Centralized metadata store with discovery' },
      { id: 'e38', text: 'Generate column-level encryption for sensitive fields', description: 'Field-level encryption implementation' },
      { id: 'e39', text: 'Create a cost estimation for processing this data', description: 'Compute and storage cost modeling' },
      { id: 'e40', text: 'Write a data sampling strategy for large datasets', description: 'Representative sampling with stratification' },
      { id: 'e41', text: 'Design an event-driven data architecture', description: 'Event sourcing with CQRS patterns' },
      { id: 'e42', text: 'Generate a CI/CD pipeline for data transformations', description: 'Automated testing and deployment for data code' },
      { id: 'e43', text: 'Create a data observability framework', description: 'Monitoring data health across the pipeline' },
      { id: 'e44', text: 'Write a schema inference engine for unstructured data', description: 'Auto-detect schema from JSON/CSV samples' },
      { id: 'e45', text: 'Design a feature store architecture', description: 'Online and offline feature serving system' },
      { id: 'e46', text: 'Generate a data governance framework', description: 'Policies, roles, and compliance controls' },
      { id: 'e47', text: 'Create a data access control matrix', description: 'RBAC policies for data assets' },
      { id: 'e48', text: 'Write a columnar storage optimization plan', description: 'Parquet/ORC format optimization' },
      { id: 'e49', text: 'Design a real-time feature computation pipeline', description: 'Streaming feature engineering architecture' },
      { id: 'e50', text: 'Generate a comprehensive data dictionary', description: 'Column definitions, business rules, and examples' },
      { id: 'e51', text: 'Create a data migration plan between systems', description: 'Zero-downtime migration strategy' },
    ],
  },
  {
    id: 'mlops',
    label: 'MLOps',
    icon: 'Settings',
    prompts: [
      { id: 'm1', text: 'Create a model deployment plan for production', description: 'Containerized model serving architecture' },
      { id: 'm2', text: 'Design a model monitoring and drift detection system', description: 'Feature and prediction drift tracking' },
      { id: 'm3', text: 'Generate a CI/CD pipeline for ML model training', description: 'Automated retraining and validation workflow' },
      { id: 'm4', text: 'Create a model registry entry with versioning', description: 'Model lifecycle management documentation' },
      { id: 'm5', text: 'Design an A/B testing framework for model comparison', description: 'Statistical testing for model deployment' },
      { id: 'm6', text: 'Write a model performance monitoring dashboard spec', description: 'KPIs, metrics, and alerting thresholds' },
      { id: 'm7', text: 'Create a feature store design for online serving', description: 'Low-latency feature retrieval architecture' },
      { id: 'm8', text: 'Design a model rollback strategy', description: 'Safe rollback procedures with canary releases' },
      { id: 'm9', text: 'Generate model serving infrastructure with autoscaling', description: 'Kubernetes-based model serving' },
      { id: 'm10', text: 'Create an experiment tracking setup with MLflow', description: 'Experiment logging and comparison framework' },
      { id: 'm11', text: 'Design a data drift detection pipeline', description: 'Statistical drift monitoring with alerts' },
      { id: 'm12', text: 'Write a model retraining trigger system', description: 'Performance-based automatic retraining' },
      { id: 'm13', text: 'Create a model explainability report for stakeholders', description: 'Business-friendly model interpretation' },
      { id: 'm14', text: 'Design a shadow deployment for new models', description: 'Parallel scoring without user impact' },
      { id: 'm15', text: 'Generate a model cost analysis for inference', description: 'GPU/CPU cost per prediction estimation' },
      { id: 'm16', text: 'Create a model governance checklist', description: 'Compliance, bias, and fairness audit' },
      { id: 'm17', text: 'Design a champion-challenger model framework', description: 'Production model comparison strategy' },
      { id: 'm18', text: 'Write a model latency optimization plan', description: 'Inference speed improvement techniques' },
      { id: 'm19', text: 'Create a batch prediction pipeline', description: 'Scheduled batch inference architecture' },
      { id: 'm20', text: 'Design a model interpretability framework', description: 'LIME, SHAP, and permutation importance' },
      { id: 'm21', text: 'Generate a model validation report', description: 'Statistical validation with holdout testing' },
      { id: 'm22', text: 'Create an edge deployment strategy for ML models', description: 'Model compression and edge inference' },
      { id: 'm23', text: 'Design a feature pipeline with versioning', description: 'Feature computation with reproducibility' },
      { id: 'm24', text: 'Write a model bias and fairness audit', description: 'Demographic parity and equalized odds analysis' },
      { id: 'm25', text: 'Create a multi-model serving architecture', description: 'Model ensemble serving with routing' },
      { id: 'm26', text: 'Design a model caching strategy for low latency', description: 'Prediction caching with invalidation' },
      { id: 'm27', text: 'Generate a model training cost optimization plan', description: 'Spot instances, mixed precision, early stopping' },
      { id: 'm28', text: 'Create a model artifact storage strategy', description: 'Model binary versioning and retrieval' },
      { id: 'm29', text: 'Design a real-time prediction pipeline', description: 'Stream processing for live predictions' },
      { id: 'm30', text: 'Write a model SLA and performance contract', description: 'Latency, throughput, and accuracy SLAs' },
      { id: 'm31', text: 'Create a model debugging and error analysis framework', description: 'Prediction error categorization and diagnosis' },
      { id: 'm32', text: 'Design an online learning pipeline', description: 'Continuous model updating with streaming data' },
      { id: 'm33', text: 'Generate a model security assessment', description: 'Adversarial attack resistance evaluation' },
      { id: 'm34', text: 'Create a model deprecation and sunsetting plan', description: 'Graceful model retirement process' },
      { id: 'm35', text: 'Design a prediction logging and audit trail', description: 'Inference logging for compliance' },
      { id: 'm36', text: 'Write a GPU resource allocation strategy', description: 'GPU sharing and scheduling optimization' },
      { id: 'm37', text: 'Create a model health check system', description: 'Liveness and readiness probes for models' },
      { id: 'm38', text: 'Design a model testing pyramid', description: 'Unit, integration, and system tests for ML' },
      { id: 'm39', text: 'Generate a model documentation template', description: 'Standardized model card with all metadata' },
      { id: 'm40', text: 'Create a data pipeline SLA monitoring system', description: 'Pipeline health and freshness tracking' },
      { id: 'm41', text: 'Design a model feature flag system', description: 'Gradual rollout with feature toggles' },
      { id: 'm42', text: 'Write a model performance alerting system', description: 'Automated alerts for metric degradation' },
      { id: 'm43', text: 'Create a reproducible training environment', description: 'Docker + conda + pinned dependencies' },
      { id: 'm44', text: 'Design a multi-region model deployment', description: 'Geo-distributed inference with failover' },
      { id: 'm45', text: 'Generate a model compliance report for regulations', description: 'GDPR, CCPA, and industry-specific compliance' },
      { id: 'm46', text: 'Create a model versioning strategy with semantic versioning', description: 'Breaking vs non-breaking model changes' },
      { id: 'm47', text: 'Design a prediction monitoring dashboard', description: 'Real-time prediction distribution tracking' },
      { id: 'm48', text: 'Write a model incident response playbook', description: 'Steps for handling model failures in production' },
      { id: 'm49', text: 'Create a model warm-up and cold start strategy', description: 'Pre-loading models for instant inference' },
      { id: 'm50', text: 'Design a model feedback loop system', description: 'Human-in-the-loop for continuous improvement' },
      { id: 'm51', text: 'Generate an end-to-end MLOps maturity assessment', description: 'Current state evaluation with improvement roadmap' },
    ],
  },
  {
    id: 'others',
    label: 'Others',
    icon: 'Layers',
    prompts: [
      { id: 'o1', text: 'Explain this dataset to a non-technical stakeholder', description: 'Plain English data summary for business users' },
      { id: 'o2', text: 'Generate a data-driven presentation outline', description: 'Slide structure with key findings' },
      { id: 'o3', text: 'Create a data ethics review for this dataset', description: 'Privacy, bias, and fairness assessment' },
      { id: 'o4', text: 'Write a project proposal based on this data', description: 'Business case with expected outcomes' },
      { id: 'o5', text: 'Design a dashboard mockup for key metrics', description: 'Dashboard layout with KPI widgets' },
      { id: 'o6', text: 'Generate interview questions for a data analyst role', description: 'Role-specific technical questions' },
      { id: 'o7', text: 'Create a data literacy training outline', description: 'Educational content for non-technical teams' },
      { id: 'o8', text: 'Write a blog post analyzing trends in this data', description: 'Content creation from data insights' },
      { id: 'o9', text: 'Design a KPI framework based on this dataset', description: 'Key performance indicator hierarchy' },
      { id: 'o10', text: 'Generate a competitive analysis template', description: 'Benchmarking framework with data points' },
      { id: 'o11', text: 'Create a risk assessment based on data patterns', description: 'Risk scoring and mitigation strategies' },
      { id: 'o12', text: 'Write a data-informed business strategy memo', description: 'Strategic recommendations from data' },
      { id: 'o13', text: 'Design an executive dashboard with this data', description: 'C-suite level KPI visualization' },
      { id: 'o14', text: 'Generate customer segmentation personas', description: 'Data-driven persona creation' },
      { id: 'o15', text: 'Create a forecasting report for next quarter', description: 'Trend-based business predictions' },
      { id: 'o16', text: 'Write a data quality improvement roadmap', description: 'Phased plan for better data quality' },
      { id: 'o17', text: 'Design a data-driven marketing strategy', description: 'Campaign optimization with data' },
      { id: 'o18', text: 'Generate a compliance audit checklist', description: 'Regulatory compliance verification' },
      { id: 'o19', text: 'Create a supply chain analysis from this data', description: 'Logistics and inventory optimization' },
      { id: 'o20', text: 'Write a financial analysis summary', description: 'Revenue, cost, and profitability insights' },
      { id: 'o21', text: 'Design an experiment plan for hypothesis testing', description: 'A/B test design with sample size calculation' },
      { id: 'o22', text: 'Generate a customer churn prediction framework', description: 'Churn indicators and prevention strategy' },
      { id: 'o23', text: 'Create a workforce analytics report', description: 'HR data insights and recommendations' },
      { id: 'o24', text: 'Write a product analytics framework', description: 'User behavior and feature adoption metrics' },
      { id: 'o25', text: 'Design a pricing optimization analysis', description: 'Price elasticity and revenue maximization' },
      { id: 'o26', text: 'Generate a social media analytics report', description: 'Engagement metrics and trend analysis' },
      { id: 'o27', text: 'Create a healthcare data analysis framework', description: 'Patient outcome and clinical metrics' },
      { id: 'o28', text: 'Write a real estate market analysis', description: 'Property trends and valuation factors' },
      { id: 'o29', text: 'Design a fraud detection strategy', description: 'Anomaly patterns and rule-based detection' },
      { id: 'o30', text: 'Generate an environmental impact analysis', description: 'Sustainability metrics and carbon footprint' },
      { id: 'o31', text: 'Create a sports analytics breakdown', description: 'Performance metrics and predictions' },
      { id: 'o32', text: 'Write an education data analysis report', description: 'Student performance and learning patterns' },
      { id: 'o33', text: 'Design a retail analytics framework', description: 'Sales, inventory, and customer insights' },
      { id: 'o34', text: 'Generate a logistics optimization plan', description: 'Route and delivery efficiency analysis' },
      { id: 'o35', text: 'Create a cybersecurity threat analysis', description: 'Threat patterns and vulnerability assessment' },
      { id: 'o36', text: 'Write a telecommunications network analysis', description: 'Network performance and capacity planning' },
      { id: 'o37', text: 'Design an IoT data processing framework', description: 'Sensor data aggregation and analysis' },
      { id: 'o38', text: 'Generate a climate data analysis', description: 'Weather patterns and environmental trends' },
      { id: 'o39', text: 'Create a manufacturing quality analysis', description: 'Defect rates and process optimization' },
      { id: 'o40', text: 'Write a transportation data analysis', description: 'Traffic patterns and route optimization' },
      { id: 'o41', text: 'Design a customer lifetime value model', description: 'CLV calculation and segmentation' },
      { id: 'o42', text: 'Generate a market basket analysis', description: 'Product affinity and cross-sell opportunities' },
      { id: 'o43', text: 'Create a web analytics deep dive', description: 'User journey and conversion funnel analysis' },
      { id: 'o44', text: 'Write a geospatial data analysis', description: 'Location-based patterns and mapping' },
      { id: 'o45', text: 'Design a text mining pipeline for reviews', description: 'Sentiment and topic extraction from text' },
      { id: 'o46', text: 'Generate a public health data report', description: 'Epidemiological trends and demographics' },
      { id: 'o47', text: 'Create an energy consumption analysis', description: 'Usage patterns and efficiency recommendations' },
      { id: 'o48', text: 'Write a venture capital deal flow analysis', description: 'Investment metrics and portfolio analytics' },
      { id: 'o49', text: 'Design a user experience analytics framework', description: 'UX metrics with heatmap analysis' },
      { id: 'o50', text: 'Generate a benchmarking study against industry standards', description: 'Performance comparison with industry averages' },
      { id: 'o51', text: 'Create a data monetization strategy', description: 'Revenue opportunities from data assets' },
    ],
  },
];
