// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-sample-datasets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/sample-datasets.ts
var salesData = [
  { region: "North", product: "Widget A", revenue: 12400, quantity: 62, date: "2024-01-15", customer_type: "Enterprise" },
  { region: "South", product: "Widget B", revenue: 8900, quantity: 45, date: "2024-01-18", customer_type: "SMB" },
  { region: "East", product: "Widget A", revenue: 15600, quantity: 78, date: "2024-01-22", customer_type: "Enterprise" },
  { region: "West", product: "Widget C", revenue: 6200, quantity: 31, date: "2024-02-01", customer_type: "Consumer" },
  { region: "North", product: "Widget B", revenue: 11300, quantity: 57, date: "2024-02-05", customer_type: "SMB" },
  { region: "South", product: "Widget A", revenue: 9800, quantity: 49, date: "2024-02-10", customer_type: "Enterprise" },
  { region: "East", product: "Widget C", revenue: 14200, quantity: 71, date: "2024-02-14", customer_type: "Consumer" },
  { region: "West", product: "Widget A", revenue: 7500, quantity: 38, date: "2024-02-20", customer_type: "SMB" },
  { region: "North", product: "Widget C", revenue: 18900, quantity: 95, date: "2024-03-01", customer_type: "Enterprise" },
  { region: "South", product: "Widget B", revenue: 5400, quantity: 27, date: "2024-03-05", customer_type: "Consumer" },
  { region: "East", product: "Widget A", revenue: 16800, quantity: 84, date: "2024-03-10", customer_type: "Enterprise" },
  { region: "West", product: "Widget B", revenue: 10200, quantity: 51, date: "2024-03-15", customer_type: "SMB" },
  { region: "North", product: "Widget A", revenue: 21e3, quantity: 105, date: "2024-03-20", customer_type: "Enterprise" },
  { region: "South", product: "Widget C", revenue: 4300, quantity: 22, date: "2024-03-25", customer_type: "Consumer" },
  { region: "East", product: "Widget B", revenue: 13100, quantity: 66, date: "2024-04-01", customer_type: "SMB" },
  { region: "West", product: "Widget C", revenue: 8700, quantity: 44, date: "2024-04-05", customer_type: "Enterprise" },
  { region: "North", product: "Widget B", revenue: 19500, quantity: 98, date: "2024-04-10", customer_type: "Enterprise" },
  { region: "South", product: "Widget A", revenue: 11800, quantity: 59, date: "2024-04-15", customer_type: "SMB" },
  { region: "East", product: "Widget C", revenue: 7200, quantity: 36, date: "2024-04-20", customer_type: "Consumer" },
  { region: "West", product: "Widget A", revenue: 14900, quantity: 75, date: "2024-04-25", customer_type: "Enterprise" }
];
var hrData = [
  { name: "Alice Chen", department: "Engineering", salary: 125e3, years: 5, performance: "Exceeds", gender: "F" },
  { name: "Bob Smith", department: "Marketing", salary: 82e3, years: 3, performance: "Meets", gender: "M" },
  { name: "Carol Wu", department: "Engineering", salary: 145e3, years: 8, performance: "Exceeds", gender: "F" },
  { name: "Dave Jones", department: "Sales", salary: 95e3, years: 6, performance: "Exceeds", gender: "M" },
  { name: "Eve Brown", department: "HR", salary: 78e3, years: 2, performance: "Meets", gender: "F" },
  { name: "Frank Lee", department: "Engineering", salary: 135e3, years: 7, performance: "Meets", gender: "M" },
  { name: "Grace Kim", department: "Marketing", salary: 88e3, years: 4, performance: "Exceeds", gender: "F" },
  { name: "Hank Davis", department: "Sales", salary: 72e3, years: 1, performance: "Below", gender: "M" },
  { name: "Iris Patel", department: "Engineering", salary: 155e3, years: 10, performance: "Exceeds", gender: "F" },
  { name: "Jack Wilson", department: "HR", salary: 85e3, years: 5, performance: "Meets", gender: "M" },
  { name: "Kate Moore", department: "Sales", salary: 91e3, years: 4, performance: "Meets", gender: "F" },
  { name: "Leo Garcia", department: "Engineering", salary: 118e3, years: 3, performance: "Meets", gender: "M" },
  { name: "Mia Taylor", department: "Marketing", salary: 96e3, years: 6, performance: "Exceeds", gender: "F" },
  { name: "Nick Adams", department: "Sales", salary: 105e3, years: 7, performance: "Exceeds", gender: "M" },
  { name: "Olivia White", department: "HR", salary: 92e3, years: 8, performance: "Meets", gender: "F" },
  { name: "Paul Harris", department: "Engineering", salary: 142e3, years: 9, performance: "Exceeds", gender: "M" },
  { name: "Quinn Clark", department: "Marketing", salary: 74e3, years: 1, performance: "Below", gender: "F" },
  { name: "Ryan Lewis", department: "Sales", salary: 88e3, years: 3, performance: "Meets", gender: "M" },
  { name: "Sara Allen", department: "Engineering", salary: 128e3, years: 6, performance: "Meets", gender: "F" },
  { name: "Tom Young", department: "HR", salary: 69e3, years: 1, performance: "Below", gender: "M" }
];
var stockData = [
  { date: "2024-01-02", open: 185.2, high: 188.4, low: 184.1, close: 187.6, volume: 425e5 },
  { date: "2024-01-03", open: 187.6, high: 189.2, low: 185.8, close: 186.3, volume: 382e5 },
  { date: "2024-01-04", open: 186.3, high: 187.9, low: 183.5, close: 184.1, volume: 451e5 },
  { date: "2024-01-05", open: 184.1, high: 186.7, low: 183.2, close: 185.9, volume: 398e5 },
  { date: "2024-01-08", open: 185.9, high: 190.3, low: 185.4, close: 189.8, volume: 512e5 },
  { date: "2024-01-09", open: 189.8, high: 192.1, low: 188.6, close: 191.5, volume: 487e5 },
  { date: "2024-01-10", open: 191.5, high: 193.8, low: 190.2, close: 192.9, volume: 443e5 },
  { date: "2024-01-11", open: 192.9, high: 194.5, low: 191.7, close: 193.2, volume: 416e5 },
  { date: "2024-01-12", open: 193.2, high: 195.1, low: 192.4, close: 194.8, volume: 469e5 },
  { date: "2024-01-16", open: 194.8, high: 196.3, low: 193.1, close: 195.7, volume: 521e5 },
  { date: "2024-01-17", open: 195.7, high: 197.2, low: 194.5, close: 196.1, volume: 475e5 },
  { date: "2024-01-18", open: 196.1, high: 198.4, low: 195.3, close: 197.8, volume: 493e5 },
  { date: "2024-01-19", open: 197.8, high: 199.1, low: 196.2, close: 198.5, volume: 538e5 },
  { date: "2024-01-22", open: 198.5, high: 200.7, low: 197.8, close: 200.2, volume: 582e5 },
  { date: "2024-01-23", open: 200.2, high: 201.5, low: 198.9, close: 199.4, volume: 456e5 },
  { date: "2024-01-24", open: 199.4, high: 202.3, low: 199.1, close: 201.8, volume: 519e5 },
  { date: "2024-01-25", open: 201.8, high: 203.6, low: 200.5, close: 202.9, volume: 484e5 },
  { date: "2024-01-26", open: 202.9, high: 204.1, low: 201.3, close: 203.5, volume: 447e5 },
  { date: "2024-01-29", open: 203.5, high: 205.8, low: 202.7, close: 205.1, volume: 553e5 },
  { date: "2024-01-30", open: 205.1, high: 206.4, low: 203.9, close: 204.6, volume: 478e5 }
];

// src/lib/mcp/tools/list-sample-datasets.ts
var list_sample_datasets_default = defineTool2({
  name: "list_sample_datasets",
  title: "List sample datasets",
  description: "List the built-in public sample datasets available in FINESE AI (sales, HR, stock) with row counts, column names, and a small preview.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const datasets = [
      { id: "sales", name: "Sales Data", data: salesData },
      { id: "hr", name: "HR Data", data: hrData },
      { id: "stock", name: "Stock Data", data: stockData }
    ].map((d) => ({
      id: d.id,
      name: d.name,
      rowCount: d.data.length,
      columns: Object.keys(d.data[0] ?? {}),
      preview: d.data.slice(0, 3)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(datasets, null, 2) }],
      structuredContent: { datasets }
    };
  }
});

// src/lib/mcp/tools/get-sample-dataset.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var MAP = {
  sales: { name: "Sales Data", data: salesData },
  hr: { name: "HR Data", data: hrData },
  stock: { name: "Stock Data", data: stockData }
};
var get_sample_dataset_default = defineTool3({
  name: "get_sample_dataset",
  title: "Get sample dataset",
  description: "Return the full rows of a built-in public sample dataset (sales, hr, or stock).",
  inputSchema: {
    id: z2.enum(["sales", "hr", "stock"]).describe("Which sample dataset to fetch."),
    limit: z2.number().int().positive().max(500).optional().describe("Optional max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id, limit }) => {
    const ds = MAP[id];
    const rows = limit ? ds.data.slice(0, limit) : ds.data;
    const payload = { id, name: ds.name, rowCount: rows.length, columns: Object.keys(ds.data[0] ?? {}), rows };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-prompt-sectors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/sample-prompts.ts
var promptSectors = [
  {
    id: "analysis",
    label: "Data Analysis",
    icon: "BarChart3",
    prompts: [
      { id: "a1", text: "Profile all columns and summarize data quality", description: "Full column-level profiling with types, nulls, and distributions" },
      { id: "a2", text: "Show the distribution of each numeric column", description: "Histograms and density plots for all numeric features" },
      { id: "a3", text: "Find the top 10 most correlated feature pairs", description: "Pearson correlation matrix with ranked pairs" },
      { id: "a4", text: "Identify all missing values and suggest imputation strategies", description: "Null analysis with MCAR/MAR/MNAR classification" },
      { id: "a5", text: "Detect outliers using IQR and Z-score methods", description: "Multi-method outlier detection with flagging" },
      { id: "a6", text: "Generate a comprehensive summary statistics table", description: "Mean, median, mode, std, skewness, kurtosis per column" },
      { id: "a7", text: "Create a pivot table grouped by the top categorical column", description: "Aggregated pivot with counts and percentages" },
      { id: "a8", text: "Show value counts for all categorical columns", description: "Frequency tables with bar chart visualizations" },
      { id: "a9", text: "Calculate the skewness and kurtosis of all numeric features", description: "Distribution shape analysis for normality assessment" },
      { id: "a10", text: "Run a time series decomposition if there is a date column", description: "Trend, seasonality, and residual components" },
      { id: "a11", text: "Compare distributions across different groups in the data", description: "Group-wise statistical comparisons" },
      { id: "a12", text: "Find duplicate rows and assess their impact", description: "Exact and fuzzy duplicate detection" },
      { id: "a13", text: "Create a correlation heatmap for all numeric columns", description: "Visual correlation matrix with color coding" },
      { id: "a14", text: "Perform a Pareto analysis on the top categorical column", description: "80/20 rule analysis with cumulative chart" },
      { id: "a15", text: "Generate box plots for all numeric columns", description: "Five-number summary visualization" },
      { id: "a16", text: "Identify columns with low variance that could be dropped", description: "Near-constant feature detection" },
      { id: "a17", text: "Show the data types and memory usage of each column", description: "Schema inspection with optimization suggestions" },
      { id: "a18", text: "Calculate percentile ranks for the target column", description: "Percentile distribution analysis" },
      { id: "a19", text: "Run a chi-squared test between categorical columns", description: "Statistical independence testing" },
      { id: "a20", text: "Create scatter plots for the top 5 most correlated pairs", description: "Visual relationship exploration" },
      { id: "a21", text: "Analyze the cardinality of each column", description: "Unique value counts and high-cardinality flagging" },
      { id: "a22", text: "Show the first and last 20 rows side by side", description: "Head/tail comparison for data inspection" },
      { id: "a23", text: "Calculate rolling averages for numeric time series columns", description: "Moving average trend analysis" },
      { id: "a24", text: "Segment the data into quantile-based bins", description: "Equal-frequency binning for numeric columns" },
      { id: "a25", text: "Find columns that are perfectly correlated (redundant)", description: "Multicollinearity detection" },
      { id: "a26", text: "Generate a data quality scorecard", description: "Completeness, accuracy, consistency metrics" },
      { id: "a27", text: "Perform cohort analysis if timestamps are available", description: "User/entity cohort tracking over time" },
      { id: "a28", text: "Run ANOVA across groups for numeric columns", description: "Analysis of variance for group differences" },
      { id: "a29", text: "Create a cumulative distribution function plot", description: "CDF visualization for numeric features" },
      { id: "a30", text: "Identify seasonal patterns in the data", description: "Seasonality detection with autocorrelation" },
      { id: "a31", text: "Compare before and after distributions for a transformation", description: "Distribution comparison with KS test" },
      { id: "a32", text: "Calculate the coefficient of variation for all numeric columns", description: "Relative variability measurement" },
      { id: "a33", text: "Find the most common patterns in string columns", description: "Regex pattern extraction and frequency analysis" },
      { id: "a34", text: "Generate a detailed null pattern matrix", description: "Missingness co-occurrence visualization" },
      { id: "a35", text: "Create a violin plot for key numeric columns", description: "Distribution shape with density estimation" },
      { id: "a36", text: "Perform a Grubbs test for outlier detection", description: "Statistical outlier test with significance levels" },
      { id: "a37", text: "Analyze the entropy of categorical columns", description: "Information content and randomness measurement" },
      { id: "a38", text: "Build a cross-tabulation between two categorical columns", description: "Contingency table with marginal totals" },
      { id: "a39", text: "Calculate Cramers V for all categorical pairs", description: "Association strength between categoricals" },
      { id: "a40", text: "Show the rate of change over time for numeric columns", description: "First derivative analysis for trends" },
      { id: "a41", text: "Create a pair plot for the top 6 numeric features", description: "Scatterplot matrix with histograms" },
      { id: "a42", text: "Identify potential data entry errors in string columns", description: "Typo and inconsistency detection" },
      { id: "a43", text: "Perform a normality test on all numeric columns", description: "Shapiro-Wilk and Anderson-Darling tests" },
      { id: "a44", text: "Calculate the Gini coefficient for inequality analysis", description: "Distribution inequality measurement" },
      { id: "a45", text: "Show the top 10 rows by each numeric column", description: "Extreme value inspection" },
      { id: "a46", text: "Analyze weekday vs weekend patterns if dates exist", description: "Day-of-week behavioral analysis" },
      { id: "a47", text: "Create a sunburst chart for hierarchical categorical data", description: "Multi-level categorical breakdown" },
      { id: "a48", text: "Run a Mann-Whitney U test between two groups", description: "Non-parametric group comparison" },
      { id: "a49", text: "Calculate mutual information between all feature pairs", description: "Non-linear dependency measurement" },
      { id: "a50", text: "Generate an executive summary of the dataset in plain English", description: "Business-friendly data overview" },
      { id: "a51", text: "Identify the most predictive features for a target variable", description: "Feature importance ranking" },
      { id: "a52", text: "Show year-over-year growth rates", description: "Annual growth trend analysis" }
    ]
  },
  {
    id: "science",
    label: "Data Science",
    icon: "Brain",
    prompts: [
      { id: "s1", text: "Suggest the best ML model for this dataset", description: "Auto-ML style model recommendation based on data shape" },
      { id: "s2", text: "Build a classification model and show the confusion matrix", description: "End-to-end classifier with evaluation metrics" },
      { id: "s3", text: "Perform feature importance analysis using Random Forest", description: "Tree-based feature ranking with visualization" },
      { id: "s4", text: "Run PCA and visualize the first two principal components", description: "Dimensionality reduction with explained variance" },
      { id: "s5", text: "Build a regression model and evaluate R\xB2, MAE, RMSE", description: "Regression pipeline with comprehensive metrics" },
      { id: "s6", text: "Perform k-means clustering and show cluster profiles", description: "Unsupervised segmentation with centroids" },
      { id: "s7", text: "Generate a train/test split strategy for this data", description: "Stratified splitting with cross-validation plan" },
      { id: "s8", text: "Create an XGBoost model with hyperparameter tuning", description: "Gradient boosting with grid search" },
      { id: "s9", text: "Build a neural network architecture for this dataset", description: "Deep learning model design with layer specs" },
      { id: "s10", text: "Perform SHAP analysis to explain model predictions", description: "Explainable AI with feature attribution" },
      { id: "s11", text: "Run a logistic regression with odds ratio interpretation", description: "Interpretable classification with coefficients" },
      { id: "s12", text: "Apply SMOTE to handle class imbalance", description: "Synthetic oversampling for imbalanced datasets" },
      { id: "s13", text: "Build a time series forecasting model", description: "ARIMA/Prophet-style prediction pipeline" },
      { id: "s14", text: "Create a recommendation system based on this data", description: "Collaborative or content-based filtering" },
      { id: "s15", text: "Perform hierarchical clustering with dendrogram", description: "Agglomerative clustering visualization" },
      { id: "s16", text: "Run a decision tree and visualize the rules", description: "Interpretable tree with decision paths" },
      { id: "s17", text: "Apply LASSO regularization for feature selection", description: "L1 penalty for sparse feature identification" },
      { id: "s18", text: "Build an ensemble model combining multiple algorithms", description: "Stacking or voting classifier design" },
      { id: "s19", text: "Perform sentiment analysis if text columns exist", description: "NLP sentiment scoring pipeline" },
      { id: "s20", text: "Create learning curves to diagnose bias vs variance", description: "Model complexity analysis" },
      { id: "s21", text: "Apply t-SNE for high-dimensional visualization", description: "Non-linear dimensionality reduction" },
      { id: "s22", text: "Build a Bayesian model for uncertainty quantification", description: "Probabilistic predictions with credible intervals" },
      { id: "s23", text: "Design a cross-validation strategy with k-fold", description: "Robust model evaluation pipeline" },
      { id: "s24", text: "Perform association rule mining (Apriori)", description: "Market basket analysis with support/confidence" },
      { id: "s25", text: "Build a survival analysis model if time-to-event data exists", description: "Kaplan-Meier and Cox proportional hazards" },
      { id: "s26", text: "Create ROC curves and calculate AUC for classifiers", description: "Classification threshold analysis" },
      { id: "s27", text: "Apply polynomial feature engineering and evaluate impact", description: "Non-linear feature transformation" },
      { id: "s28", text: "Build a Naive Bayes classifier for text data", description: "Probabilistic text classification" },
      { id: "s29", text: "Perform topic modeling with LDA on text columns", description: "Latent topic discovery in text data" },
      { id: "s30", text: "Create a model comparison table across 5 algorithms", description: "Head-to-head model benchmarking" },
      { id: "s31", text: "Apply KNN with distance metric optimization", description: "Nearest neighbor classification/regression" },
      { id: "s32", text: "Build an autoencoder for anomaly detection", description: "Deep learning anomaly scoring" },
      { id: "s33", text: "Perform Granger causality testing", description: "Temporal causal relationship analysis" },
      { id: "s34", text: "Create precision-recall curves for imbalanced classes", description: "Imbalanced classification evaluation" },
      { id: "s35", text: "Build a gradient boosted regression with early stopping", description: "Optimized boosting with regularization" },
      { id: "s36", text: "Apply IsolationForest for unsupervised anomaly detection", description: "Tree-based outlier scoring" },
      { id: "s37", text: "Generate a model card documenting the best model", description: "Standardized model documentation" },
      { id: "s38", text: "Perform ablation study removing features one at a time", description: "Feature contribution analysis" },
      { id: "s39", text: "Build a calibration curve for probability predictions", description: "Prediction reliability assessment" },
      { id: "s40", text: "Apply embedding techniques for categorical variables", description: "Entity embedding for high-cardinality features" },
      { id: "s41", text: "Create a stacked generalization ensemble", description: "Meta-learner combining base models" },
      { id: "s42", text: "Perform Bayesian hyperparameter optimization", description: "Efficient search with Gaussian processes" },
      { id: "s43", text: "Build a multi-output prediction model", description: "Simultaneous multi-target regression" },
      { id: "s44", text: "Apply DBSCAN for density-based clustering", description: "Non-parametric cluster detection" },
      { id: "s45", text: "Create partial dependence plots for top features", description: "Feature effect visualization" },
      { id: "s46", text: "Build a pipeline with preprocessing and model training", description: "End-to-end sklearn pipeline design" },
      { id: "s47", text: "Perform statistical power analysis for sample size", description: "Minimum sample size calculation" },
      { id: "s48", text: "Apply data augmentation techniques for small datasets", description: "Synthetic data generation strategies" },
      { id: "s49", text: "Build a multi-class classifier with one-vs-rest strategy", description: "Multi-class classification pipeline" },
      { id: "s50", text: "Generate a reproducible experiment report", description: "Full experiment documentation with metrics" },
      { id: "s51", text: "Perform feature interaction analysis", description: "Detect synergistic feature combinations" }
    ]
  },
  {
    id: "engineering",
    label: "Data Engineering",
    icon: "Wrench",
    prompts: [
      { id: "e1", text: "Design a data pipeline architecture for this dataset", description: "ETL/ELT pipeline design with stages" },
      { id: "e2", text: "Generate SQL CREATE TABLE statements from this schema", description: "DDL generation with proper types and constraints" },
      { id: "e3", text: "Create a feature engineering plan for ML readiness", description: "Feature transformation and creation strategy" },
      { id: "e4", text: "Write data validation rules for each column", description: "Schema validation with Great Expectations style" },
      { id: "e5", text: "Design a data partitioning strategy for scalability", description: "Partition key selection and scheme design" },
      { id: "e6", text: "Generate a dbt model for transforming this data", description: "dbt SQL model with tests and documentation" },
      { id: "e7", text: "Create an Airflow DAG for this data pipeline", description: "Orchestration workflow with tasks and dependencies" },
      { id: "e8", text: "Write data quality checks and assertions", description: "Automated quality gates with pass/fail criteria" },
      { id: "e9", text: "Design a CDC (Change Data Capture) strategy", description: "Incremental data capture pipeline design" },
      { id: "e10", text: "Generate a star schema from this flat dataset", description: "Dimensional modeling with fact and dimension tables" },
      { id: "e11", text: "Create a data catalog entry for this dataset", description: "Metadata documentation with lineage" },
      { id: "e12", text: "Write Python code to clean and standardize this data", description: "Data cleansing pipeline with pandas" },
      { id: "e13", text: "Design an idempotent data loading strategy", description: "Upsert and merge patterns for reliability" },
      { id: "e14", text: "Generate a Spark job for processing this data at scale", description: "PySpark transformation code" },
      { id: "e15", text: "Create data lineage documentation", description: "Source-to-target mapping with transformations" },
      { id: "e16", text: "Write unit tests for the data transformations", description: "pytest-based data pipeline testing" },
      { id: "e17", text: "Design a data lakehouse architecture", description: "Bronze/Silver/Gold layer design" },
      { id: "e18", text: "Generate a schema migration plan for evolving data", description: "Backward-compatible schema evolution strategy" },
      { id: "e19", text: "Create a data anonymization plan for PII columns", description: "Masking, hashing, and tokenization strategies" },
      { id: "e20", text: "Write a streaming pipeline design for real-time data", description: "Kafka/Kinesis architecture with processing" },
      { id: "e21", text: "Design a slowly changing dimension (SCD) strategy", description: "Type 1/2/3 SCD implementation plan" },
      { id: "e22", text: "Generate indexes and optimization for query performance", description: "Index strategy with query pattern analysis" },
      { id: "e23", text: "Create a data retention and archival policy", description: "Lifecycle management with compliance" },
      { id: "e24", text: "Write a data deduplication pipeline", description: "Exact and fuzzy matching dedup strategy" },
      { id: "e25", text: "Design a multi-tenant data architecture", description: "Tenant isolation with shared infrastructure" },
      { id: "e26", text: "Generate a Terraform config for data infrastructure", description: "IaC for data platform resources" },
      { id: "e27", text: "Create a data contract for this dataset", description: "Producer-consumer agreement with SLAs" },
      { id: "e28", text: "Write a backfill strategy for historical data", description: "Batch processing for missing historical records" },
      { id: "e29", text: "Design a data mesh domain boundary", description: "Domain-driven data ownership model" },
      { id: "e30", text: "Generate a monitoring dashboard config for pipelines", description: "Metrics, alerts, and SLA tracking" },
      { id: "e31", text: "Create a data versioning strategy", description: "Dataset version control with DVC or similar" },
      { id: "e32", text: "Write ETL error handling and retry logic", description: "Fault-tolerant pipeline patterns" },
      { id: "e33", text: "Design a data warehouse schema for analytics", description: "Optimized warehouse with materialized views" },
      { id: "e34", text: "Generate a REST API design for serving this data", description: "API endpoints with pagination and filtering" },
      { id: "e35", text: "Create a data freshness monitoring system", description: "Staleness detection with alerting" },
      { id: "e36", text: "Write a data reconciliation check between source and target", description: "Row count and checksum validation" },
      { id: "e37", text: "Design a metadata management strategy", description: "Centralized metadata store with discovery" },
      { id: "e38", text: "Generate column-level encryption for sensitive fields", description: "Field-level encryption implementation" },
      { id: "e39", text: "Create a cost estimation for processing this data", description: "Compute and storage cost modeling" },
      { id: "e40", text: "Write a data sampling strategy for large datasets", description: "Representative sampling with stratification" },
      { id: "e41", text: "Design an event-driven data architecture", description: "Event sourcing with CQRS patterns" },
      { id: "e42", text: "Generate a CI/CD pipeline for data transformations", description: "Automated testing and deployment for data code" },
      { id: "e43", text: "Create a data observability framework", description: "Monitoring data health across the pipeline" },
      { id: "e44", text: "Write a schema inference engine for unstructured data", description: "Auto-detect schema from JSON/CSV samples" },
      { id: "e45", text: "Design a feature store architecture", description: "Online and offline feature serving system" },
      { id: "e46", text: "Generate a data governance framework", description: "Policies, roles, and compliance controls" },
      { id: "e47", text: "Create a data access control matrix", description: "RBAC policies for data assets" },
      { id: "e48", text: "Write a columnar storage optimization plan", description: "Parquet/ORC format optimization" },
      { id: "e49", text: "Design a real-time feature computation pipeline", description: "Streaming feature engineering architecture" },
      { id: "e50", text: "Generate a comprehensive data dictionary", description: "Column definitions, business rules, and examples" },
      { id: "e51", text: "Create a data migration plan between systems", description: "Zero-downtime migration strategy" }
    ]
  },
  {
    id: "mlops",
    label: "MLOps",
    icon: "Settings",
    prompts: [
      { id: "m1", text: "Create a model deployment plan for production", description: "Containerized model serving architecture" },
      { id: "m2", text: "Design a model monitoring and drift detection system", description: "Feature and prediction drift tracking" },
      { id: "m3", text: "Generate a CI/CD pipeline for ML model training", description: "Automated retraining and validation workflow" },
      { id: "m4", text: "Create a model registry entry with versioning", description: "Model lifecycle management documentation" },
      { id: "m5", text: "Design an A/B testing framework for model comparison", description: "Statistical testing for model deployment" },
      { id: "m6", text: "Write a model performance monitoring dashboard spec", description: "KPIs, metrics, and alerting thresholds" },
      { id: "m7", text: "Create a feature store design for online serving", description: "Low-latency feature retrieval architecture" },
      { id: "m8", text: "Design a model rollback strategy", description: "Safe rollback procedures with canary releases" },
      { id: "m9", text: "Generate model serving infrastructure with autoscaling", description: "Kubernetes-based model serving" },
      { id: "m10", text: "Create an experiment tracking setup with MLflow", description: "Experiment logging and comparison framework" },
      { id: "m11", text: "Design a data drift detection pipeline", description: "Statistical drift monitoring with alerts" },
      { id: "m12", text: "Write a model retraining trigger system", description: "Performance-based automatic retraining" },
      { id: "m13", text: "Create a model explainability report for stakeholders", description: "Business-friendly model interpretation" },
      { id: "m14", text: "Design a shadow deployment for new models", description: "Parallel scoring without user impact" },
      { id: "m15", text: "Generate a model cost analysis for inference", description: "GPU/CPU cost per prediction estimation" },
      { id: "m16", text: "Create a model governance checklist", description: "Compliance, bias, and fairness audit" },
      { id: "m17", text: "Design a champion-challenger model framework", description: "Production model comparison strategy" },
      { id: "m18", text: "Write a model latency optimization plan", description: "Inference speed improvement techniques" },
      { id: "m19", text: "Create a batch prediction pipeline", description: "Scheduled batch inference architecture" },
      { id: "m20", text: "Design a model interpretability framework", description: "LIME, SHAP, and permutation importance" },
      { id: "m21", text: "Generate a model validation report", description: "Statistical validation with holdout testing" },
      { id: "m22", text: "Create an edge deployment strategy for ML models", description: "Model compression and edge inference" },
      { id: "m23", text: "Design a feature pipeline with versioning", description: "Feature computation with reproducibility" },
      { id: "m24", text: "Write a model bias and fairness audit", description: "Demographic parity and equalized odds analysis" },
      { id: "m25", text: "Create a multi-model serving architecture", description: "Model ensemble serving with routing" },
      { id: "m26", text: "Design a model caching strategy for low latency", description: "Prediction caching with invalidation" },
      { id: "m27", text: "Generate a model training cost optimization plan", description: "Spot instances, mixed precision, early stopping" },
      { id: "m28", text: "Create a model artifact storage strategy", description: "Model binary versioning and retrieval" },
      { id: "m29", text: "Design a real-time prediction pipeline", description: "Stream processing for live predictions" },
      { id: "m30", text: "Write a model SLA and performance contract", description: "Latency, throughput, and accuracy SLAs" },
      { id: "m31", text: "Create a model debugging and error analysis framework", description: "Prediction error categorization and diagnosis" },
      { id: "m32", text: "Design an online learning pipeline", description: "Continuous model updating with streaming data" },
      { id: "m33", text: "Generate a model security assessment", description: "Adversarial attack resistance evaluation" },
      { id: "m34", text: "Create a model deprecation and sunsetting plan", description: "Graceful model retirement process" },
      { id: "m35", text: "Design a prediction logging and audit trail", description: "Inference logging for compliance" },
      { id: "m36", text: "Write a GPU resource allocation strategy", description: "GPU sharing and scheduling optimization" },
      { id: "m37", text: "Create a model health check system", description: "Liveness and readiness probes for models" },
      { id: "m38", text: "Design a model testing pyramid", description: "Unit, integration, and system tests for ML" },
      { id: "m39", text: "Generate a model documentation template", description: "Standardized model card with all metadata" },
      { id: "m40", text: "Create a data pipeline SLA monitoring system", description: "Pipeline health and freshness tracking" },
      { id: "m41", text: "Design a model feature flag system", description: "Gradual rollout with feature toggles" },
      { id: "m42", text: "Write a model performance alerting system", description: "Automated alerts for metric degradation" },
      { id: "m43", text: "Create a reproducible training environment", description: "Docker + conda + pinned dependencies" },
      { id: "m44", text: "Design a multi-region model deployment", description: "Geo-distributed inference with failover" },
      { id: "m45", text: "Generate a model compliance report for regulations", description: "GDPR, CCPA, and industry-specific compliance" },
      { id: "m46", text: "Create a model versioning strategy with semantic versioning", description: "Breaking vs non-breaking model changes" },
      { id: "m47", text: "Design a prediction monitoring dashboard", description: "Real-time prediction distribution tracking" },
      { id: "m48", text: "Write a model incident response playbook", description: "Steps for handling model failures in production" },
      { id: "m49", text: "Create a model warm-up and cold start strategy", description: "Pre-loading models for instant inference" },
      { id: "m50", text: "Design a model feedback loop system", description: "Human-in-the-loop for continuous improvement" },
      { id: "m51", text: "Generate an end-to-end MLOps maturity assessment", description: "Current state evaluation with improvement roadmap" }
    ]
  },
  {
    id: "others",
    label: "Others",
    icon: "Layers",
    prompts: [
      { id: "o1", text: "Explain this dataset to a non-technical stakeholder", description: "Plain English data summary for business users" },
      { id: "o2", text: "Generate a data-driven presentation outline", description: "Slide structure with key findings" },
      { id: "o3", text: "Create a data ethics review for this dataset", description: "Privacy, bias, and fairness assessment" },
      { id: "o4", text: "Write a project proposal based on this data", description: "Business case with expected outcomes" },
      { id: "o5", text: "Design a dashboard mockup for key metrics", description: "Dashboard layout with KPI widgets" },
      { id: "o6", text: "Generate interview questions for a data analyst role", description: "Role-specific technical questions" },
      { id: "o7", text: "Create a data literacy training outline", description: "Educational content for non-technical teams" },
      { id: "o8", text: "Write a blog post analyzing trends in this data", description: "Content creation from data insights" },
      { id: "o9", text: "Design a KPI framework based on this dataset", description: "Key performance indicator hierarchy" },
      { id: "o10", text: "Generate a competitive analysis template", description: "Benchmarking framework with data points" },
      { id: "o11", text: "Create a risk assessment based on data patterns", description: "Risk scoring and mitigation strategies" },
      { id: "o12", text: "Write a data-informed business strategy memo", description: "Strategic recommendations from data" },
      { id: "o13", text: "Design an executive dashboard with this data", description: "C-suite level KPI visualization" },
      { id: "o14", text: "Generate customer segmentation personas", description: "Data-driven persona creation" },
      { id: "o15", text: "Create a forecasting report for next quarter", description: "Trend-based business predictions" },
      { id: "o16", text: "Write a data quality improvement roadmap", description: "Phased plan for better data quality" },
      { id: "o17", text: "Design a data-driven marketing strategy", description: "Campaign optimization with data" },
      { id: "o18", text: "Generate a compliance audit checklist", description: "Regulatory compliance verification" },
      { id: "o19", text: "Create a supply chain analysis from this data", description: "Logistics and inventory optimization" },
      { id: "o20", text: "Write a financial analysis summary", description: "Revenue, cost, and profitability insights" },
      { id: "o21", text: "Design an experiment plan for hypothesis testing", description: "A/B test design with sample size calculation" },
      { id: "o22", text: "Generate a customer churn prediction framework", description: "Churn indicators and prevention strategy" },
      { id: "o23", text: "Create a workforce analytics report", description: "HR data insights and recommendations" },
      { id: "o24", text: "Write a product analytics framework", description: "User behavior and feature adoption metrics" },
      { id: "o25", text: "Design a pricing optimization analysis", description: "Price elasticity and revenue maximization" },
      { id: "o26", text: "Generate a social media analytics report", description: "Engagement metrics and trend analysis" },
      { id: "o27", text: "Create a healthcare data analysis framework", description: "Patient outcome and clinical metrics" },
      { id: "o28", text: "Write a real estate market analysis", description: "Property trends and valuation factors" },
      { id: "o29", text: "Design a fraud detection strategy", description: "Anomaly patterns and rule-based detection" },
      { id: "o30", text: "Generate an environmental impact analysis", description: "Sustainability metrics and carbon footprint" },
      { id: "o31", text: "Create a sports analytics breakdown", description: "Performance metrics and predictions" },
      { id: "o32", text: "Write an education data analysis report", description: "Student performance and learning patterns" },
      { id: "o33", text: "Design a retail analytics framework", description: "Sales, inventory, and customer insights" },
      { id: "o34", text: "Generate a logistics optimization plan", description: "Route and delivery efficiency analysis" },
      { id: "o35", text: "Create a cybersecurity threat analysis", description: "Threat patterns and vulnerability assessment" },
      { id: "o36", text: "Write a telecommunications network analysis", description: "Network performance and capacity planning" },
      { id: "o37", text: "Design an IoT data processing framework", description: "Sensor data aggregation and analysis" },
      { id: "o38", text: "Generate a climate data analysis", description: "Weather patterns and environmental trends" },
      { id: "o39", text: "Create a manufacturing quality analysis", description: "Defect rates and process optimization" },
      { id: "o40", text: "Write a transportation data analysis", description: "Traffic patterns and route optimization" },
      { id: "o41", text: "Design a customer lifetime value model", description: "CLV calculation and segmentation" },
      { id: "o42", text: "Generate a market basket analysis", description: "Product affinity and cross-sell opportunities" },
      { id: "o43", text: "Create a web analytics deep dive", description: "User journey and conversion funnel analysis" },
      { id: "o44", text: "Write a geospatial data analysis", description: "Location-based patterns and mapping" },
      { id: "o45", text: "Design a text mining pipeline for reviews", description: "Sentiment and topic extraction from text" },
      { id: "o46", text: "Generate a public health data report", description: "Epidemiological trends and demographics" },
      { id: "o47", text: "Create an energy consumption analysis", description: "Usage patterns and efficiency recommendations" },
      { id: "o48", text: "Write a venture capital deal flow analysis", description: "Investment metrics and portfolio analytics" },
      { id: "o49", text: "Design a user experience analytics framework", description: "UX metrics with heatmap analysis" },
      { id: "o50", text: "Generate a benchmarking study against industry standards", description: "Performance comparison with industry averages" },
      { id: "o51", text: "Create a data monetization strategy", description: "Revenue opportunities from data assets" }
    ]
  }
];

// src/lib/mcp/tools/list-prompt-sectors.ts
var list_prompt_sectors_default = defineTool4({
  name: "list_prompt_sectors",
  title: "List prompt sectors",
  description: "List the public prompt library sectors (Data Analysis, Data Science, Data Engineering, MLOps, etc.) with prompt counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const sectors = promptSectors.map((s) => ({ id: s.id, label: s.label, promptCount: s.prompts.length }));
    return {
      content: [{ type: "text", text: JSON.stringify(sectors, null, 2) }],
      structuredContent: { sectors }
    };
  }
});

// src/lib/mcp/tools/get-sample-prompts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_sample_prompts_default = defineTool5({
  name: "get_sample_prompts",
  title: "Get sample prompts",
  description: "Return the full list of curated sample prompts for a given sector (analysis, science, engineering, mlops, other).",
  inputSchema: {
    sectorId: z3.string().describe("Sector id from list_prompt_sectors."),
    limit: z3.number().int().positive().max(200).optional().describe("Optional max prompts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ sectorId, limit }) => {
    const sector = promptSectors.find((s) => s.id === sectorId);
    if (!sector) {
      return {
        content: [{ type: "text", text: `Unknown sector "${sectorId}". Call list_prompt_sectors first.` }],
        isError: true
      };
    }
    const prompts = limit ? sector.prompts.slice(0, limit) : sector.prompts;
    const payload = { id: sector.id, label: sector.label, prompts };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/about-finese.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
var about_finese_default = defineTool6({
  name: "about_finese",
  title: "About FINESE AI",
  description: "Return a short description of FINESE AI, its capabilities, and the modes it supports.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const about = {
      name: "FINESE AI",
      tagline: "Chat-first AI data intelligence for data professionals.",
      capabilities: [
        "Automatic dataset profiling (types, nulls, outliers, correlations)",
        "Server-side statistical compute via tool-calls",
        "Chart, table, profile, stats, hypothesis, pivot, and code artifacts",
        "Feature importance, confusion matrix, model card, drift, and pipeline artifacts",
        "Debugging, experiment design, data storytelling, and documentation modes",
        "In-browser Python execution via Pyodide"
      ],
      sectors: ["Data Analysis", "Data Science", "Data Engineering", "MLOps", "Other"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(about, null, 2) }],
      structuredContent: about
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "finese-ai-mcp",
  title: "FINESE AI",
  version: "0.1.0",
  instructions: "Public tools for FINESE AI, a chat-first data intelligence platform. Use `about_finese` for an overview, `list_sample_datasets` / `get_sample_dataset` to explore built-in sample data (sales, HR, stock), and `list_prompt_sectors` / `get_sample_prompts` to browse the curated prompt library across data analysis, data science, data engineering, and MLOps. `echo` verifies connectivity.",
  tools: [
    about_finese_default,
    echo_default,
    list_sample_datasets_default,
    get_sample_dataset_default,
    list_prompt_sectors_default,
    get_sample_prompts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
