// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-sample-datasets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { salesData, hrData, stockData } from "npm:@/lib/sample-datasets";
var list_sample_datasets_default = defineTool2({
  name: "list_sample_datasets",
  title: "List sample datasets",
  description: "List the built-in public sample datasets available in FINESE AI (sales, HR, stock) with row counts, column names, and a small preview.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const datasets = [
      { id: "sales", name: "Sales Data", data: salesData },
      { id: "hr", name: "HR Data", data: hrData },
      { id: "stock", name: "Stock Data", data: stockData }
    ].map((d) => ({
      id: d.id,
      name: d.name,
      rowCount: d.data.length,
      columns: Object.keys(d.data[0] ?? {}),
      preview: d.data.slice(0, 3)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(datasets, null, 2) }],
      structuredContent: { datasets }
    };
  }
});

// src/lib/mcp/tools/get-sample-dataset.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { salesData as salesData2, hrData as hrData2, stockData as stockData2 } from "npm:@/lib/sample-datasets";
var MAP = {
  sales: { name: "Sales Data", data: salesData2 },
  hr: { name: "HR Data", data: hrData2 },
  stock: { name: "Stock Data", data: stockData2 }
};
var get_sample_dataset_default = defineTool3({
  name: "get_sample_dataset",
  title: "Get sample dataset",
  description: "Return the full rows of a built-in public sample dataset (sales, hr, or stock).",
  inputSchema: {
    id: z2.enum(["sales", "hr", "stock"]).describe("Which sample dataset to fetch."),
    limit: z2.number().int().positive().max(500).optional().describe("Optional max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id, limit }) => {
    const ds = MAP[id];
    const rows = limit ? ds.data.slice(0, limit) : ds.data;
    const payload = { id, name: ds.name, rowCount: rows.length, columns: Object.keys(ds.data[0] ?? {}), rows };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-prompt-sectors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { promptSectors } from "npm:@/lib/sample-prompts";
var list_prompt_sectors_default = defineTool4({
  name: "list_prompt_sectors",
  title: "List prompt sectors",
  description: "List the public prompt library sectors (Data Analysis, Data Science, Data Engineering, MLOps, etc.) with prompt counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const sectors = promptSectors.map((s) => ({ id: s.id, label: s.label, promptCount: s.prompts.length }));
    return {
      content: [{ type: "text", text: JSON.stringify(sectors, null, 2) }],
      structuredContent: { sectors }
    };
  }
});

// src/lib/mcp/tools/get-sample-prompts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { promptSectors as promptSectors2 } from "npm:@/lib/sample-prompts";
var get_sample_prompts_default = defineTool5({
  name: "get_sample_prompts",
  title: "Get sample prompts",
  description: "Return the full list of curated sample prompts for a given sector (analysis, science, engineering, mlops, other).",
  inputSchema: {
    sectorId: z3.string().describe("Sector id from list_prompt_sectors."),
    limit: z3.number().int().positive().max(200).optional().describe("Optional max prompts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ sectorId, limit }) => {
    const sector = promptSectors2.find((s) => s.id === sectorId);
    if (!sector) {
      return {
        content: [{ type: "text", text: `Unknown sector "${sectorId}". Call list_prompt_sectors first.` }],
        isError: true
      };
    }
    const prompts = limit ? sector.prompts.slice(0, limit) : sector.prompts;
    const payload = { id: sector.id, label: sector.label, prompts };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/about-finese.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
var about_finese_default = defineTool6({
  name: "about_finese",
  title: "About FINESE AI",
  description: "Return a short description of FINESE AI, its capabilities, and the modes it supports.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const about = {
      name: "FINESE AI",
      tagline: "Chat-first AI data intelligence for data professionals.",
      capabilities: [
        "Automatic dataset profiling (types, nulls, outliers, correlations)",
        "Server-side statistical compute via tool-calls",
        "Chart, table, profile, stats, hypothesis, pivot, and code artifacts",
        "Feature importance, confusion matrix, model card, drift, and pipeline artifacts",
        "Debugging, experiment design, data storytelling, and documentation modes",
        "In-browser Python execution via Pyodide"
      ],
      sectors: ["Data Analysis", "Data Science", "Data Engineering", "MLOps", "Other"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(about, null, 2) }],
      structuredContent: about
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "finese-ai-mcp",
  title: "FINESE AI",
  version: "0.1.0",
  instructions: "Public tools for FINESE AI, a chat-first data intelligence platform. Use `about_finese` for an overview, `list_sample_datasets` / `get_sample_dataset` to explore built-in sample data (sales, HR, stock), and `list_prompt_sectors` / `get_sample_prompts` to browse the curated prompt library across data analysis, data science, data engineering, and MLOps. `echo` verifies connectivity.",
  tools: [
    about_finese_default,
    echo_default,
    list_sample_datasets_default,
    get_sample_dataset_default,
    list_prompt_sectors_default,
    get_sample_prompts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
